--- 
- name: Install filebeat
  hosts: all
  become: yes
  become_user: root
  tasks:
    - block: 
      - name: Istall filebeat repo on centos 6
        shell: "curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-x86_64.rpm"
      - name: Install from rpm
        shell: rpm -vi filebeat-7.1.1-x86_64.rpm
        notify: FIREBEAT_CENTOS_6
      when: ansible_distribution =="CentOS" and ansible_distribution == "6"
      


    - block: 
      - name: Istall filebeat repo on centos 7
        shell: "curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-x86_64.rpm"
      - name: Install from rpm
        shell: rpm -vi filebeat-7.1.1-x86_64.rpm
        notify: FIREBEAT_CENTOS_7
      when: ansible_distribution =="CentOS" and ansible_distribution == "7"
      
  
  handlers: 
    - name: FIREBEAT_CENTOS_6
      service:
        name: filebeat
        state: restarted
    - name: FIREBEAT_CENTOS_7
      service:
        name: filebeat
        state: restarted   
