---  
- name: Provision Centos7
  hosts: localhost
  tasks:

    - name: Launch CentOS7
      ec2:
        aws_region: us-east-2
        image: ami-0f2b4fc905b0bd1f1
        instance_type: t2.micro
        instance_tags:
          Name: CentOS7
        count: 1
        wait: yes
        vpc_subnet_id: subnet-0c1f6076
        assign_public_ip: yes
        key_name: awx key


    - name: update kernel to latest 
      when: ansible_distribution == "CentOS" 
      package:
        Name: kernel
        state: latest

    - name: restart the system
      when: ansible_distribution == "CentOS"
      reboot: 




    - name: Launch Ubuntu-18.04
      ec2:
        aws_region: us-east-2
        image: ami-0f2b4fc905b0bd1f1
        instance_type: t2.micro
        instance_tags:
          Name: Ubuntu-18.04
        count: 1
        wait: yes
        vpc_subnet_id: subnet-0c1f6076
        assign_public_ip: yes
        user_data: |
                   #!/bin/sh
                   sudo apt-get install python -y 
                   sudo apt-get install boto -y
        key_name: aws key



    - name: Launch Debian GNU-Linux 9
      ec2:
        aws_region: us-east-2
        image: ami-0f2b4fc905b0bd1f1
        instance_type: t2.micro
        instance_tags:
          Name: Debian GNU-Linux 9
        count: 1
        wait: yes
        vpc_subnet_id: subnet-0c1f6076
        assign_public_ip: yes
        user_data: |
                   #!/bin/sh
                   sudo apt-get install python -y
                   sudo apt-get install boto -y
        key_name: axw key


- hosts:
  - localhost

  tasks:
    - pip:
        name: boto