--- 
  - name: Install 1 package
    hosts: all
    tasks: 
      - name: install 1 package
        service:
         name: httpd
         state: present
        become: yes 
        become_method: sudo