--- 
  - name: Install 1 package
    hosts: all
    tasks: 
      - name: install 1 package
        service:
         name: httpd
         state: present
        became: yes 
        became_method: sudo